### ISSUE TITLE
Improve documentation on ssh key usage

### ISSUE THREAD

**Issue by chrislovecnm** [tbarbugli/cassandra_snapshotter#21]
Hi all

I am looking for better documentation on how to just use ssh keys, and no password.  I am getting an error from fabric that sudo requires a password.  Do I need to setup sudo on the remote boxes to all to run the backup w/o password?

Thanks

Chris

**Comment by mandeepm91** [comment]
I am also facing this issue. Running the following command from my local machine

```
cassandra-snapshotter --s3-bucket-name=<masked> \
                      --s3-bucket-region=us-east-1 \
                      --s3-base-path=<masked> \
                      --aws-access-key-id=<masked> \
                      --aws-secret-access-key=<masked> \
                      backup \
                      --hosts=<masked> \
                      --user=ubuntu

```

And have the correct ssh_config setup. Any idea what I might be doing wrong ?
