### ISSUE TITLE
add support for cassandra 2.1

### ISSUE THREAD

**Issue by tbarbugli** [tbarbugli/cassandra_snapshotter#23]
data directory structure changed

**Comment by ivanyu** [comment]
Hi!
I really want Cassandra 2.1 support and going to implement it. Could you direct me where should I start?

**Comment by tbarbugli** [comment]
afaik the main changes are related to where snapshots are stored (different naming convention). so you probably only need to change the part where the upload manifest is created. https://github.com/tbarbugli/cassandra_snapshotter/blob/master/cassandra_snapshotter/agent.py#L138 is where the list of files to upload (based on data_dir and snapshot name) is created.

**Comment by ivanyu** [comment]
What should be the signs of failure with Cassandra 2.1? I'm asking because I've tried cassandra_snapshotter from PyPI and it's backuped and listed correctly (at first glance).

**Comment by tbarbugli** [comment]
well the absence of snapshot files on S3 for once

**Comment by ivanyu** [comment]
Well, it seems to fail when a table is specified, but works correctly with keyspaces. I believe it's due to table name postfix introduced in 2.1: `glob.glob` doesn't catch it.

I think I know how to fix it. Is there an accepted way to distinguish Cassandra versions in the agent?

**Comment by tbarbugli** [comment]
There is no cassandra version detected, I think the best would be to add a
command line option to use cassandra 2.1 dir structure (unless you know a
reliable to add version discovery).
ᐧ
