### ISSUE TITLE
Update documentation for restore and other cool features

### ISSUE THREAD

**Issue by chrislovecnm** [tbarbugli/cassandra_snapshotter#27]
Hey

I will probably knock this out myself, but this awesome tool may be lacking some documentation ... #justsayin

For instance:

``
cassandra-snapshotter -v --aws-access-key-id=redacted \
  --aws-secret-access-key=redacted \
  --s3-bucket-name=your_buck_name  --s3-bucket-region=us-west-1 --s3-ssenc \
  --s3-base-path=your_base_path restore --keyspace=your_keyspace --target-hosts=cassandra01,cassandra02
``

Also add more details what happens during a restore, for instance the program is going to download the snapshot out of the s3 repo to the machine you ran the command on, and then run sstableloader.  You need disk and sstableloader.  Also what are the details on prepping the cluster?  Do you need the schema to exists?

I am thinking to provide examples of various commands, also more details on getting snapshots running properly.  I am guessing that you have to list the keyspaces to get snapshotting running correctly.

Here is an example of a list command:

``
cassandra-snapshotter -v --aws-access-key-id=redacted   \
  --aws-secret-access-key=redacted --s3-bucket-name=your_bucket_name \
  --s3-bucket-region=us-west-1 --s3-ssenc --s3-base-path=your_base_path list
``

Also we may want to link to https://help.ubuntu.com/community/SSH/OpenSSH/Keys for instructions on creating ssh shared keys.

The topics areas that I see need some TLC are:
- restore
- ssh keys
- list
- other command line switches that are not documented

Thoughts?  Comments?

**Comment by scalp42** [comment]
@tbarbugli @arikfr is there a branch somewhere with the restore working for the compressed backups?

**Comment by chrislovecnm** [comment]
Been open too long ... closing
