### ISSUE TITLE
Restore capability

### ISSUE THREAD

**Issue by chrislovecnm** [tbarbugli/cassandra_snapshotter#29]
I know that you used sstableloader for restore, or do we want to do that or just scp the file and have the agent uncompress it?

Or the agent download the files and restore itself?  A reverse of the backup

**Comment by matkam** [comment]
I'm curious about the restore procedure as well. Restore currently downloads the lzo compressed snapshot files, and uses ```sstableloader``` to restore each table. But as far as I can tell, there is nothing decompressing the lzo files. For anyone who's successfully restored from a ```cassandra_snapshotter``` backup, what's your procedure for doing so (with or without ```cassandra_snapshotter```)?

**Comment by chrislovecnm** [comment]
Been open too long ... closing
