### ISSUE TITLE
Support EC2 IAM roles

### ISSUE THREAD

**Issue by jhmartin** [tbarbugli/cassandra_snapshotter#38]
Please support usage of IAM roles [sample](http://stackoverflow.com/questions/11129976/boto-issue-with-iam-role) 

This will allow EC2 machines to utilize their machine credentials for S3 access rather than requiring an access/secret key to be hardcoded.

**Comment by jhmartin** [comment]
Yes, the IAM component would only work if run from EC2 machines, but avoiding using explicit credentials is highly desirable -- otherwise it is a hassle to re-key everything periodically.

**Comment by irlevesque** [comment]
Created https://github.com/tbarbugli/cassandra_snapshotter/pull/41 for my own purposes but saw that other people were interested. I only tested on instances with IAM, not by passing in keys.

**Comment by dimas** [comment]
So guys, it has been quite a while since that pull request was created. Are there any plans to have that support merged in?
Passing credentials in the command line is not the best idea - they are visible in "ps" output etc.

**Comment by tbarbugli** [comment]
@dimas going to have a look at this today and see if i can get it in master

**Comment by pdehlke** [comment]
*bump*

What ever happened with this?

**Comment by jhmartin** [comment]
Bump?

**Comment by jhmartin** [comment]
Did this get added via a different issue?

**Comment by tbarbugli** [comment]
yes, sorry I forgot to add it to the issue
