### ISSUE TITLE
Tag the 0.3.1 release hash

### ISSUE THREAD

**Issue by eherot** [tbarbugli/cassandra_snapshotter#49]
Based on the history of the CHANGELOG I'm guessing this is https://github.com/tbarbugli/cassandra_snapshotter/commit/e5bf7bb5a7a62f0a6368fef9b88b495b6cf81c48

**Comment by tateeskew** [comment]
I'm interested to see the new changes over the last 6 months pushed up to pypi. Any chance a new release could be pushed?

**Comment by tbarbugli** [comment]
tag created, 0.4.0 released

**Comment by tateeskew** [comment]
:+1:
