### ISSUE TITLE
conf path required by agent

### ISSUE THREAD

**Issue by bailoo** [tbarbugli/cassandra_snapshotter#51]
I get the following error when using cassandra-snapshottr
out: cassandra-snapshotter-agent create-upload-manifest: error: argument --conf_path is required

My command is
cassandra-snapshotter --aws-access-key-id=SOMETHING --aws-secret-access-key=SOMEKEY --s3-bucket-name=mybucket --s3-bucket-region=us-east-1 --s3-base-path=dirname backup --hosts=54.x.x.x --user=username

This command worked fine earlier but fails when I used pip install to get the latest on the node. 

Please help me to debug this further and fix it

**Comment by tbarbugli** [comment]
what version were you using before?

**Comment by tbarbugli** [comment]
closing this one due to inactivity
