### ISSUE TITLE
Fatal error: Needed to prompt for a connection or sudo password

### ISSUE THREAD

**Issue by zxfrank** [tbarbugli/cassandra_snapshotter#70]
I got an error when executing backup command:
```
cassandra-snapshotter --s3-bucket-name=XXXX \
                      --s3-bucket-region=us-east-1 \
                      --s3-base-path=XXXXX \
                      --aws-access-key-id=XXXXXXXXXXXX \
                      --aws-secret-access-key=XXXXXXXXXXXXXXXXXXX \
                      --s3-ssenc \
                      backup \
                      --hosts=lab_db \
                      --user=cassandra
```
[lab_db] Executing task 'node_start_backup'

Fatal error: Needed to prompt for a connection or sudo password (host: lab_db), but input would be ambiguous in parallel mode

Aborting.

Fatal error: One or more hosts failed while executing task 'node_start_backup'

Aborting.
[lab_db] Executing task 'clear_node_snapshot'
[lab_db] run: /usr/bin/nodetool clearsnapshot -t "20151211141001"

Fatal error: Needed to prompt for a connection or sudo password (host: lab_db), but input would be ambiguous in parallel mode

Aborting.

Fatal error: One or more hosts failed while executing task 'clear_node_snapshot'

Aborting.

**Comment by tbarbugli** [comment]
in order to use the tool you need to be able to ssh and use sudo on each Cassandra node from the terminal that starts the backup without a password prompt.

**Comment by zxfrank** [comment]
Oh thanks the error is amgiguous :P

**Comment by bhaveshg-cg** [comment]
I have one question is it secure to use cassandra_snapshotter tool ?
