### ISSUE TITLE
pip install cassandra_snapshotter does not work

### ISSUE THREAD

**Issue by abienkowski** [tbarbugli/cassandra_snapshotter#74]
Getting the fol;lowing error when trying to run pip install; running Fedora 23, similar issue on AMZN Linux and ubuntu.

$ pip install cassandra_snapshooter
Collecting cassandra-snapshooter
  Could not find a version that satisfies the requirement cassandra-snapshooter (from versions: )
No matching distribution found for cassandra-snapshooter

**Comment by tbarbugli** [comment]
it's cassandra_snapshotter not snapshooter ;)

**Comment by abienkowski** [comment]
Thx :)
