### ISSUE TITLE
Error><Code>InternalError</Code><Message>We encountered an internal error

### ISSUE THREAD

**Issue by asmi85** [tbarbugli/cassandra_snapshotter#85]
Hello, We are using cassandra_snapshot to take snapshots but getting the following error regularly 

 lzop 1.03
 out: LZO library 2.06
out: Copyright (C) 1996-2010 Markus Franz Xaver Johannes Oberhumer
] out: Traceback (most recent call last):
out:   File "/usr/local/bin/cassandra-snapshotter-agent", line 9, in <module>
out:     load_entry_point('cassandra-snapshotter==0.4.0', 'console_scripts', 'cassandra-snapshotter-agent')()
out:   File "/usr/local/lib/python2.7/dist-packages/cassandra_snapshotter/agent.py", line 266, in main
 out:     args.incremental_backups
out:   File "/usr/local/lib/python2.7/dist-packages/cassandra_snapshotter/agent.py", line 145, in put_from_manifest
out:     for _ in pool.imap(upload_file, ((bucket, f, destination_path(s3_base_path, f), s3_ssenc, buffer_size) for f in files)):
 out:   File "/usr/lib/python2.7/multiprocessing/pool.py", line 659, in next
out:     raise value
 out: boto.exception.S3ResponseError: S3ResponseError: 200 OK
out: <?xml version="1.0" encoding="UTF-8"?>
out: <Error><Code>InternalError</Code><Message>We encountered an internal error. Please try again.</Message><RequestId>XXXXXXXXXX</RequestId><HostId>XXXXXXXXXXXXXXXXXXXXXXX</HostId></Error>

Can someone please help why are we getting this running snapshots? We have 5 nodes each about 100 gbs of data.

**Comment by asmi85** [comment]
more info on this ..Seems like this error occurred only for 2 nodes out of 5 ..rest ran fine.

**Comment by tbarbugli** [comment]
yep, there a fix for this on master. I am going to release it this weekend

**Comment by asmi85** [comment]
Thanks so much. Can you please let me know when you release it and then i just need to update?

**Comment by asmi85** [comment]
Sorry, just checking, any updates on this when will this be released ?

**Comment by tbarbugli** [comment]
1.0.0 is available now, make sure you update your nodes to that version

**Comment by asmi85** [comment]
hello, I Updated it from git master but getting lots 
 out: cassandra_snapshotter.agent INFO     MSG: Initialized multipart upload for file  
messages in the logs..

**Comment by tbarbugli** [comment]
do you have verbose logging enabled? the message itself is OK but you should only see it if you have verbose logging enabled otherwise that's unwanted noise in your logs :)
