### ISSUE TITLE
No S3 directory when no change in keyspace ?

### ISSUE THREAD

**Issue by asmi85** [tbarbugli/cassandra_snapshotter#86]
Hey guys, I was seeing no s3 backup directory being generated when there is no change in keyspace using this package. Is that expected ?

Thanks

**Comment by tbarbugli** [comment]
can you paste the command that you use for both runs?

**Comment by asmi85** [comment]
hi @tbarbugli
This is what i used. 
cassandra-snapshotter --s3-bucket-name=XXXXX --s3-base-path=XXXXX  --s3-bucket-region=XXXXX --aws-access-key-id=XXXXX   --aws-secret-access-key=XXXXX backup --hosts=XXXXX  --user=XXXXX

**Comment by tbarbugli** [comment]
OK this is normal behavior. the tool first create a snapshot and after that syncs incremental backups (https://github.com/tbarbugli/cassandra_snapshotter#incremental-backups-1) If that's not what you want you can force new snapshot everytime
